### ISSUE TITLE
Problem with trans

### ISSUE THREAD

**Issue by DJReneOL** [rvalitov/widgetkit-grid-stack-ex#4]
Hello,
i have a problem with the translation of my widget_ex

When i got to optins of the wiget_ex all my text is in {{* | trans}}
The menu looks like this:
    {{'Layout' | trans}}
    {{'Media' | trans}}
    {{'Content' | trans}}
    {{'Lightbox' | trans}}
    {{'General' | trans}}
    {{'About' | trans}}

The problem comes after the upload to the webserver with akeeba, localy i have no issues.
I try to reinstall Widetkit and your extensions, but this doesn't resolve the Problem.

Can you help me?

**Comment by rvalitov** [comment]
Hello!
I'm really sorry, your question somehow didn't show up in my notifications!
Does this problem still happen?
Sure, I will help with this. If problem still happens, please, use the browser's console to find the errors (text in red) and post them here. Instructions how to open the console are here https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors

**Comment by rvalitov** [comment]
@DJReneOL I didn't get a reply from you. Does this issue still happen on your website?
